### ISSUE TITLE
[Bug][UI] MIUI issue with title color and contrast

### ISSUE THREAD

**Issue by OshekharO** [Jacekun/CloudStream-3XXX#34] opened 2022-03-30 10:53 UTC
**Guidelines:**
- [x] It **is not** a duplicate issue.

**To Reproduce**
1. Open The App
2. Click on 'any provider'
3. Scroll down to 'check the title'

**Expected behavior**
Well I expected the title to be seen clearly without putting extra pressure on eyes.

**Screenshots or video**
![Screenshot_2022-03-30-16-17-22-199_foss jacekun cloudstream3xxx](https://user-images.githubusercontent.com/95137948/160815011-c1587d57-efbc-4e8f-ad6d-c0b73f4e50d9.jpg)

**Device (please complete the following information):**
 - Android Version: Android 11 API 30
 - App Version: v2.8.16

**Additional context**
Please Change title color to black on homepage

**Comment by Jacekun** [comment] 2022-03-30 10:56
I can't reproduce this bug on any provider. Do you have forced theme(s) installed?

**Comment by OshekharO** [comment] 2022-03-30 11:00
No, everything is set to default. I will check on another device and report you later.

Edit: yes it's miui issue when device set to light mode everything works normally but when set to dark mode this issue happening.

**Comment by OshekharO** [comment] 2022-03-30 11:07
@Jacekun bro enable stream support for javfree.sh provider I have checked streamable link's are fetched.

**Comment by Jacekun** [comment] 2022-03-30 11:10
> @Jacekun bro enable stream support for javfree.sh provider I have checked streamable link's are fetched.

It is fetched but not playable. I'll look into it more before enabling it.

Closing issue cause its false alarm.

**Closed as completed by Jacekun** 2022-03-30 11:10 UTC
Labels: bug

**Comment by OshekharO** [comment] 2022-03-30 11:11
Bro it's playable that's why I said enable for it I have compiled the apk and tried @Jacekun

**Comment by OshekharO** [comment] 2022-03-30 11:11
If you want I can send the compiled apk here you can check yourself

**Comment by Jacekun** [comment] 2022-03-30 11:11
> Bro it's playable that's why I said enable for it I have compiled the apk and tried @Jacekun

Huh? That's neat and surprising. Will do

**Comment by OshekharO** [comment] 2022-03-30 11:16
@Jacekun make changes in your streamsb extractor from: [Stormunblessed/CloudStream-3](https://github.com/Stormunblessed/CloudStream-3/blob/master/app/src/main/java/com/lagradost/cloudstream3/extractors/StreamSB.kt)
